// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAobSxLIRXKp7WhsAcFbZTaQmSdzQarvyU',
    appId: '1:92353458248:web:38f95009662a10e786a87d',
    messagingSenderId: '92353458248',
    projectId: 'esavior-90375',
    authDomain: 'esavior-90375.firebaseapp.com',
    storageBucket: 'esavior-90375.appspot.com',
    measurementId: 'G-9FWLNVSS8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUizSPaOuwCkKlueUVs9d9CU8zS2Ux82A',
    appId: '1:92353458248:android:988526d7ade99f9986a87d',
    messagingSenderId: '92353458248',
    projectId: 'esavior-90375',
    storageBucket: 'esavior-90375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wGyNpDLQ4MgaOXMngy9OotVKj1MLJpM',
    appId: '1:92353458248:ios:342e8e510052846b86a87d',
    messagingSenderId: '92353458248',
    projectId: 'esavior-90375',
    storageBucket: 'esavior-90375.appspot.com',
    iosBundleId: 'com.example.eSavior',
  );

}